// SmartHub/SmartHub.Ui/src/components/widgets/Card.vue
<template>
  <div class="flex-1 h-full max-w-4xl mx-auto overflow-hidden bg-white rounded-lg shadow-lg dark:bg-gray-800 ">
    <div class="flex flex-col overflow-y-auto md:flex-row ">
      <slot />
    </div>
  </div>
</template>

<script>
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Card'
});
</script>

<style scoped></style>

// src/WebUI/ClientApp/src/components/ui/card/index.tsx
import clsx from 'clsx';
import React, { ReactNode } from 'react';

interface ICardProps {
  background?: ReactNode;
  children?: ReactNode;
  heigth?: string;
}

const Card = ({ background, children, heigth }: ICardProps) => {
  return (
    <div className={clsx(heigth || '', 'bg-white rounded-xl shadow-md overflow-hidden')}>
      <div className='h-full flex flex-col relative'>
        {background && <div>{background}</div>}
        {children && <div className='p-6'>{children}</div>}
      </div>
    </div>
  );
};

export default Card;
